### PR TITLE
Feature/storybook

### PR DESCRIPTION
**Pull request by lyqht**
**What this PR is for:** adding storybook to the project, supporting Vue3 Vite & TailwindCSS. 

**Why this PR:** It will helpful for users to look at lotion components in isolation now that a NPM library is available, and also assist developers maintaining the library to perform visual regression testing.

**Demo:**

lotion_storybook_demo

**Issues & Caveats:**

- Some of the components don't render nicely, but it is not really because of storybook.
- For example, BlockMenu doesn't show up at all in isolation. Hence it is not committed as part of this PR.
- Lotion component looks a bit strange, and I briefly looked at the CSS, it is because of the negative margin left applied to the BlockComponent. Refer to element inspect preview below. 
- When you hover to the left of a block, the BlockMenu within Lotion component doesn't show up aligned centered to the block. Also after you try hovering a few more times, it is not possible to see the BlockMenu anymore. Clicking on block menu items do not change the block types.

Screenshot 2022-09-01 at 1 01 04 AM

**Points of considerations**:
- The project maintainers may want to reconsider the styling of the various components in isolation.
- As part of this PR, i also added some prop types into `types.ts`. They were added to support typing the `StoryFn` and `Meta` provided by Storybook. Not sure how usually Vue structures these types in files (I haven't worked with Vue in TS before. In React usually we manually declare interfaces for Props, but here we use `defineProps`. I don't know if these defined props can be exported.)

### CODE REVIEW

**Comment by lyqht** [comment]
Any updates on this? @greentfrapp

**Comment by greentfrapp** [comment]
Looking into it! I'm new to Storybook but seems useful

**Comment by greentfrapp** [comment]
Hey @lyqht this looks like a good start, I'm merging this into a separate branch `storybook-support` for now, while we figure out how to fix the issues with looking at components in isolation

Some comments:
- This would be really useful for our own internal development too, thanks for the suggestion!
- There seems to be a surprising number of high severity vulnerabilities with installing storybook's packages

**Review by greentfrapp — APPROVED** [review]

**Comment by lyqht** [comment]
Cool, thanks for accepting the PR! Yeh not sure why storybook hasn't update all those stuff that has to do w security.
Btw fyi, the PR won't count for Hacktoberfest contributors if the repo itself is not labelled w Hacktoberfest (edit: just saw lotion has the label). 'hacktoberfest-accepted' is for maintainers that participate in Hacktoberfest and not really needed for contributors.

**Pull request merged**
